# Generated by Django 4.2 on 2023-04-22 22:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome do produto')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('price', models.IntegerField()),
                ('foto_produto', models.ImageField(upload_to='fotos/%d/%m/%Y/')),
                ('description', models.TextField(default='Sem Descrição')),
                ('data_produto', models.DateTimeField(default=datetime.datetime.now)),
                ('categoria', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('televisao', 'Televisão'), ('computador', 'Computador'), ('celular', 'Celular'), ('audio_video', 'Áudio e Vídeo')], default='eletronicos', max_length=100, verbose_name='categoria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
